### ISSUE TITLE
Allocate huge disk space for SST, but use only small part of that file.

### ISSUE THREAD

**Issue by SunguckLee** [facebook/rocksdb#3265]
I am testing "target_file_size_multiplier" option of MongoRocks.
I found that bigger target_file_size_multiplier makes mongodb use more total disk space.

This case was happened when I have added "configString: 'max_background_compactions=20;target_file_size_multiplier=4;target_file_size_base=134217728;write_buffer_size=134217728;level0_file_num_compaction_trigger=3;level0_slowdown_writes_trigger=10'" option to MongoDB.

### Expected behavior
Total data size is less than 20GB, But sometimes single SST file allocated over 600GB.
I am not sure what size is proper but not 600GB for small data.

### Actual behavior
Some SST file is allocated 685GB. 
```
# du -sh /data/mongodb/db/*
2.8G    /data/mongodb/db/000333.sst
3.2G    /data/mongodb/db/000499.sst
3.2G    /data/mongodb/db/000621.sst
2.4G    /data/mongodb/db/000708.sst
513M    /data/mongodb/db/000727.sst
301M    /data/mongodb/db/000732.sst
790M    /data/mongodb/db/000736.sst
849M    /data/mongodb/db/000741.sst
516M    /data/mongodb/db/000742.sst
122M    /data/mongodb/db/000744.sst
122M    /data/mongodb/db/000746.sst
301M    /data/mongodb/db/000747.sst
122M    /data/mongodb/db/000749.sst
685G    /data/mongodb/db/000750.sst  ==> WHY ?
122M    /data/mongodb/db/000752.sst
122M    /data/mongodb/db/000754.sst
607M    /data/mongodb/db/000755.sst
122M    /data/mongodb/db/000757.sst
4.0K    /data/mongodb/db/CURRENT
4.0K    /data/mongodb/db/IDENTITY
141M    /data/mongodb/db/journal
0       /data/mongodb/db/LOCK
1.4M    /data/mongodb/db/LOG
4.0M    /data/mongodb/db/MANIFEST-000005
8.0K    /data/mongodb/db/OPTIONS-000005
8.0K    /data/mongodb/db/OPTIONS-000008
```
But data is only resident about 1GB.
```
# ls -alh /data/mongodb/db/
total 700G
drwxr-xr-x 3 mongod mongod 4.0K Dec 12 16:15 .
drwxr-xr-x 5 mongod mongod  159 Dec 12 16:01 ..
-rw-r--r-- 1 mongod mongod 2.8G Dec 12 16:05 000333.sst
-rw-r--r-- 1 mongod mongod 3.2G Dec 12 16:09 000499.sst
-rw-r--r-- 1 mongod mongod 3.2G Dec 12 16:12 000621.sst
-rw-r--r-- 1 mongod mongod 2.4G Dec 12 16:14 000708.sst
-rw-r--r-- 1 mongod mongod 513M Dec 12 16:14 000727.sst
-rw-r--r-- 1 mongod mongod 301M Dec 12 16:14 000732.sst
-rw-r--r-- 1 mongod mongod 790M Dec 12 16:15 000736.sst
-rw-r--r-- 1 mongod mongod 849M Dec 12 16:15 000741.sst
-rw-r--r-- 1 mongod mongod 516M Dec 12 16:15 000742.sst
-rw-r--r-- 1 mongod mongod 122M Dec 12 16:15 000744.sst
-rw-r--r-- 1 mongod mongod 122M Dec 12 16:15 000746.sst
-rw-r--r-- 1 mongod mongod 301M Dec 12 16:15 000747.sst
-rw-r--r-- 1 mongod mongod 122M Dec 12 16:15 000749.sst
-rw-r--r-- 1 mongod mongod 927M Dec 12 16:15 000750.sst ==> Only use 927MB
-rw-r--r-- 1 mongod mongod 122M Dec 12 16:15 000752.sst
-rw-r--r-- 1 mongod mongod 122M Dec 12 16:15 000754.sst
-rw-r--r-- 1 mongod mongod 607M Dec 12 16:15 000755.sst
-rw-r--r-- 1 mongod mongod 122M Dec 12 16:15 000757.sst
-rw-r--r-- 1 mongod mongod   16 Dec 12 15:57 CURRENT
-rw-r--r-- 1 mongod mongod   37 Dec 12 15:56 IDENTITY
drwxr-xr-x 2 mongod mongod   24 Dec 12 16:15 journal
-rw-r--r-- 1 mongod mongod    0 Dec 12 15:56 LOCK
-rw-r--r-- 1 mongod mongod 1.3M Dec 12 16:15 LOG
-rw-r--r-- 1 mongod mongod  47K Dec 12 16:15 MANIFEST-000005
-rw-r--r-- 1 mongod mongod 4.4K Dec 12 15:56 OPTIONS-000005
-rw-r--r-- 1 mongod mongod 4.4K Dec 12 15:57 OPTIONS-000008
```

### Steps to reproduce the behavior
MongoDB configuration file
```
....
storage:
    syncPeriodSecs: 60
    dbPath: /data/mongodb
    journal:
        enabled: true
        commitIntervalMs: 100

    engine: rocksdb
    rocksdb:
        cacheSizeGB: 30
        compression: lz4
        maxWriteMBPerSec : 1024
        configString: "max_background_compactions=20;target_file_size_multiplier=4;target_file_size_base=134217728;write_buffer_size=134217728;level0_file_num_compaction_trigger=3;level0_slowdown_writes_trigger=10"
```

Join member of some replica-set (which has over 30GB disk data), then this case might happen.

And is this case something to do with "allow_fallocate" options ? Then could you share why do we need "fallocate" operation for SST file.
```
[Version]
  rocksdb_version=5.9.0
  options_file_version=1.1

[DBOptions]
  advise_random_on_open=true
  use_adaptive_mutex=false
  allow_mmap_reads=false
  allow_fallocate=true
  ...
```
